// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"learning-project/internal/app"
	"learning-project/internal/module/user/interfaces"
	"learning-project/internal/module/user/repository"
	"learning-project/internal/module/user/service"
)

// Injectors from wire.go:

func InitUserService(commons *app.AppCommons) interfaces.UserService {
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository, commons)
	return userService
}

func InitAttendanceService(commons *app.AppCommons) interfaces.AttendanceService {
	attendanceRepository := repository.NewAttendanceRepository()
	attendanceService := service.NewAttendanceService(commons, attendanceRepository)
	return attendanceService
}

// wire.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService)

var attendanceSet = wire.NewSet(repository.NewAttendanceRepository, service.NewAttendanceService)
