// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"learning-project/internal/driver"
	"learning-project/internal/module/user/interfaces"
	"learning-project/internal/module/user/repository"
	"learning-project/internal/module/user/service"
)

// Injectors from wire.go:

func InitUserService() interfaces.UserService {
	db := driver.InitDatabase()
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(db, userRepository)
	return userService
}

// wire.go:

var userSet = wire.NewSet(driver.InitDatabase, repository.NewUserRepository, service.NewUserService)
