// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"learning-project/internal/app"
)

// Injectors from wire.go:

func InitLogger() *app.Logger {
	logger := app.NewLogger()
	return logger
}

// wire.go:

var logProvider = wire.NewSet(app.NewLogger)
