// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"learning-project/internal/app"
	"learning-project/internal/driver"
)

// Injectors from wire.go:

func InitApp() *app.AppCommons {
	db := driver.InitDatabase()
	logger := app.NewLogger()
	validator := app.NewValidator()
	connection := driver.NewRabbitMQConnection()
	appCommons := app.NewAppCommons(db, logger, validator, connection)
	return appCommons
}

// wire.go:

var appWireSet = wire.NewSet(app.NewLogger, app.NewAppCommons, app.NewValidator, driver.InitDatabase, driver.NewRabbitMQConnection)
